app/Http/routes.php
<?php
//RUTAS DEL FRONT-END

Route::get('/',[
	'as'   => 'front.index',
	'uses' => 'IndexController@index'
]);

Route::get('mail',[
    'uses' => 'MailController@store',
    'as'  => 'mail.store'
]);

Route::get('mail/{name}/{email}/{mensajeContact}','MailController@store');

Route::get('admin/login', 'Auth\AuthController@showLoginForm');

Route::get('categories/{name}',[
'uses' => 'IndexController@searchCategory',
 'as'  => 'index.search.category'
]);

Route::get('tags/{name}',[
    'uses' => 'IndexController@searchTag',
    'as'  => 'index.search.tag'
]);

Route::get('articles/{category}/{slug}',[
    'uses' => 'IndexController@ViewArticle',
    'as'   => 'index.view.article'
]);

/*Route::get('articles',[
'as' => 'articles',
'uses' => 'UserController@index'
]);*/

//RUTAS DEL PANEL DE ADMINISTRACIÓN.

Route::group(['prefix' => 'admin','middleware' => 'auth'], function() {

	Route::get('/',function(){
		return view('home');
	});


	Route::get('/home',function(){
		return view('home');
	});

	Route::group(['middleware'=>'admin'],function()
	{
		Route::resource('users', 'UsersController');
		Route::get('users/{id}/destroy',[
			'uses' => 'UsersController@destroy',
			'as'   => 'admin.users.destroy'
		]);
	});

	Route::resource('categories', 'CategoriesController');
    Route::get('categories/{id}/destroy',
    		[
    	'uses' => 'CategoriesController@destroy',
    	'as' => 'admin.categories.destroy'

    		]);
	Route::resource('tags', 'TagsController');
	Route::get('tags/{id}/destroy',
		[
			'uses' => 'TagsController@destroy',
			'as' => 'admin.tags.destroy'

		]);

	Route::resource('phrases', 'PhrasesController');
	Route::get('phrases/{id}/destroy',
		[
			'uses' => 'PhrasesController@destroy',
			'as' => 'admin.phrases.destroy'

		]);

	Route::resource('articles', 'ArticlesController');
	Route::get('articles/{id}/destroy',
		[
			'uses' => 'ArticlesController@destroy',
			'as' => 'admin.articles.destroy'

		]);

	Route::get('welcome',[
		'uses' => 'HomeController@index',
		'as'   => 'admin.home.index'
	]);

	Route::get('Images',[
	'uses' => 'ImagesController@index',
	'as'   => 'admin.images.index'
	]);

});

// Authentication Routes...
Route::get('/admin/login', 'Auth\AuthController@showLoginForm');
Route::post('/admin/login', 'Auth\AuthController@login');
Route::get('/admin/logout', 'Auth\AuthController@logout');

// Password Reset Routes...
Route::get('/admin/password/reset/{token?}', 'Auth\PasswordController@showResetForm');
Route::post('/admin/password/email', 'Auth\PasswordController@sendResetLinkEmail');
Route::post('/admin/password/reset', 'Auth\PasswordController@reset');

resources/views/admin/template/partials/errors.blade.php
@if(count($errors) > 0)
    <div class="alert alert-danger" role="alert">
	<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <ul>
            @foreach($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/admin/template/partials/metadatos.blade.php
    @if(App::environment('local'))

          <script src="{{ asset('plugins/jquery/js/jquery.2.1.3.min.js') }}"></script>
          <script type="text/javascript" src="{{ asset('plugins/bootstrap/js/bootstrap.min.js') }}"></script>
    
    @else
          <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.3/jquery.min.js" integrity="sha384-I6F5OKECLVtK/BL+8iSLDEHowSAfUo76ZL9+kGAgTRdiByINKJaqTPH/QVNS1VDb" crossorigin="anonymous"></script>
          <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script> 

    @endif

        <script src="{{ asset('js/funciones.js') }}"></script>

        <!-- bxSlider Javascript file -->
        <script src="{{ asset('plugins/bxslider/jquery.bxslider.min.js') }}"></script>
        <!-- bxSlider CSS file -->
        <link href="{{ asset('plugins/bxslider/jquery.bxslider.css') }}" rel="stylesheet" />

        <script type="text/javascript" src="{{ asset('plugins/Jquery-UI/jquery-ui.js') }}"></script>

    @if(App::environment('local'))

         <link rel="stylesheet" href="{{ asset('plugins/fonts/font-waesome/css/font-awesome.min.css') }}">
         <link rel="stylesheet" href="{{ asset('plugins/bootstrap/css/bootstrap.css') }}">

    @else
        <!-- Fonts -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css" integrity="sha384-XdYbMnZ/QjLh6iI4ogqCTaIjrFk87ip+ekIjefZch0Y+PvJ8CDYtEs1ipDmPorQ+" crossorigin="anonymous">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700">

        <!-- Styles -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
        {{-- <link href="{{ elixir('css/app.css') }}" rel="stylesheet"> --}}

    @endif

    <style>

    body{
        cursor: url({{ asset('plugins/mouse/left_ptr.cur') }}),auto !important;

    }
    body a:hover
    {
        cursor: url({{ asset('plugins/mouse/pointing_hand.cur') }}),pointer !important;

    }

    #Textbuscar
    {

        cursor:url({{ asset('plugins/mouse/Text.cur') }}), text !important;
    }
    #boton_buscar
    {
        cursor: url({{ asset('plugins/mouse/pointing_hand.cur') }}),pointer !important;

    }

</style>

resources/views/admin/template/partials/nav.blade.php
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{{ URL::to('/') }}" target="_blank">Eury Rodr&iacute;guez</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="{{ route('admin.home.index') }}">Inicio <span class="glyphicon glyphicon-home"></span></a></li>
       @if(Auth::user()->admin())
        <li><a href="{{ route('admin.users.index') }}">Usuarios <i class="fa fa-users fa-lg" aria-hidden="true"></i> </a></li>
       @endif
        <li><a href="{{ route('admin.categories.index') }}">Categor&iacute;as <span class="glyphicon glyphicon-th-list"></span></a></li>
        <li><a href="{{ route('admin.articles.index') }}">Artículos <span class="glyphicon glyphicon-pencil"></span></a></li>
        <li><a href="{{ route('admin.images.index') }}">Imágenes <span class=" glyphicon glyphicon-picture"></span></a></li>
        <li><a href="{{ route('admin.tags.index') }}">Etiquetas <span class="glyphicon glyphicon-tags"></span></a></li>
        <li><a href="{{ route('admin.phrases.index') }} ">Frases <i class="fa fa-quote-right fa-lg" aria-hidden="true"></i></a> </li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" style="color: #000;font-weight: bold" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ Auth::user()->name }} &nbsp;<span class="glyphicon glyphicon-user"></span><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{{ url('admin/logout') }}"><i class="fa fa-btn fa-sign-out"></i>
                Cerrar Sesi&oacute;n</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>